### ISSUE TITLE
whats up with plasma-pa (/Audio Volume) settings?

### ISSUE THREAD

**Issue by ahjolinna** [PapirusDevelopmentTeam/adapta-kde#34]
my system:
```
inxi -Sx
System:    Host: arch-anywhere Kernel: 4.14.12-3-ck-skylake x86_64 bits: 64 gcc: 7.2.1
           Desktop: KDE Plasma 5.11.5 (Qt 5.10.0) Distro: Arch Linux
```

I have adapta-kde git version and kvantum-qt5-git from aur (did test the "stable" versions) and yes I'm using the whole adapta (nokto) theme, and for some reason plasma-pa setting (or Audio Volume Settings) looks like this for me:

this is basic (light)adapta:
![image](https://user-images.githubusercontent.com/6993072/34746108-928ed78c-f59b-11e7-94c5-1bfdb33aa875.png)

![image](https://user-images.githubusercontent.com/6993072/34746192-c6c0c8a8-f59b-11e7-908f-7ad6cef5f2c3.png)
 
![image](https://user-images.githubusercontent.com/6993072/34746159-ad80a67e-f59b-11e7-8988-8f108e8ec9c5.png)

![image](https://user-images.githubusercontent.com/6993072/34746258-01d7cc02-f59c-11e7-967d-38c211bd73f1.png)
![image](https://user-images.githubusercontent.com/6993072/34746274-12321828-f59c-11e7-8720-020ba8336497.png)

the (dark) adapta nokto

![image](https://user-images.githubusercontent.com/6993072/34746736-d45c0e8a-f59d-11e7-9108-33bb24a8049f.png)
![image](https://user-images.githubusercontent.com/6993072/34746745-e4efefb4-f59d-11e7-9dfd-9da9de94e543.png)
![image](https://user-images.githubusercontent.com/6993072/34746768-f9cc01e8-f59d-11e7-9a2b-d3b2a556a798.png)

**Comment by varlesh** [comment]
It's reproduced with Breeze Dark too:
![image](https://user-images.githubusercontent.com/8083855/34756779-96384ad0-f5e6-11e7-954f-2233c1090a06.png)
I think it's style hardcoded (some elements on Plasma hardcoded)

**Comment by varlesh** [comment]
Similar bug: https://github.com/PapirusDevelopmentTeam/adapta-kde/issues/26

**Comment by varlesh** [comment]
@tsujan For info, it's similar bug with #26.
Menuitem not used from Kvantum on plasma-pa settings **Volume-Additional-Profile**

**Comment by varlesh** [comment]
Kvantum Default Theme:
![image](https://user-images.githubusercontent.com/8083855/34757202-241f9d06-f5e9-11e7-8fb9-79cc49fdc89c.png)

**Comment by varlesh** [comment]
It's very strange widget LOL. Some elements used from Plasma theme, see checkbox

**Comment by tsujan** [comment]
@varlesh Since such issues are reproducible with dark Breeze themes, they should be reported at KDE bug tracker. The sooner KDE devs know about them, the better.

**Comment by tsujan** [comment]
It' a shame that KDE can't provide a self-consistent look. Qt has so many widgets and they can be subclassed in so many consistent ways but yet, KDE have bad widgets that may look OK only with light themes. KDE4 didn't have this problem -- no to this extent, at least. I think it's a side effect of using QML. QML has ruined the look of Plasma5, IMO.

**Comment by varlesh** [comment]
Dark theme supported really for check only.
See, it's really like as mockup or raw concept:
![image](https://user-images.githubusercontent.com/8083855/34762462-511a9352-f601-11e7-8db7-a53a7d1c25c6.png)
And compare with Oxygen:
![image](https://user-images.githubusercontent.com/8083855/34762571-a5e3eb22-f601-11e7-8ccf-4a495323b85a.png)

**Comment by varlesh** [comment]
reported: https://bugs.kde.org/show_bug.cgi?id=388766

**Comment by varlesh** [comment]
@nowrep I'm sorry for disturbing you, but you developer plasma-pa and maybe fix that...

**Comment by nowrep** [comment]
I did fix it before, but it was broken again with move to QtQuickControls 2.

**Comment by tsujan** [comment]
This is what we use under LXQt. It's called `pavucontrol-qt` and has a clean Qt interface, like that of the gtk-based `pavucontrol`:

![pavucontrol-qt](https://user-images.githubusercontent.com/981076/34768965-930f26e6-f611-11e7-994e-4f0bbbdba3c2.png)

**Comment by tsujan** [comment]
Since this isn't the first time such problems arise and it won't be the last time either, I feel a short explanation is needed:

Qt apps are styled by `QStyle`. Many QStyle functions have `QWidget` as an argument. That argument is used for adjusting the details of the style and fine tuning the looks and feels. However, QML doesn't have `QWidget` -- it reports a NULL `QWidget` in QStyle functions. Worse than that, some QML "widgets" are drawn in a weird way. For example, line-edits and combos are "stretched" in the middle, so that they can't have very rounded corners. For these reasons, a QML app can only have the most elementary look.

Plasma5 developers made Breeze to give all QML and non-QML apps a uniform (ugly) look because QML couldn't have a nice look. Why did they start to use QML, in the first place? They've said different things about that in different places. As far as I remember, one reason was that QML supposedly made kwin lighter.

Anyhow, QML is inferior to Qt and the toll of using it is big. We still don't have a decent titlebar for Kwin -- Breeze doesn't support the most elementary properties like translucency or custom gradient and many users prefer Aurorae over it. Why KDE devs has been indifferent to such matters for such a long time, I don't know.

**Comment by nowrep** [comment]
@tsujan 
    However, QML doesn't have QWidget -- it reports a NULL QWidget in QStyle functions

You can get the QQuickItem by casting it from `QStyleOption::styleObject`, that's how Breeze fine-tune rendering of QtQuickControls 1 widgets so they look the same as QWidgets.

**Comment by tsujan** [comment]
> You can get the QQuickItem by casting it from QStyleOption::styleObject

Not enough; the problem is deeper than that.

> that's how Breeze fine-tune rendering of QtQuickControls1 items so they look the same as QWidgets.

Quite conversely, Breeze makes the appearance of QWidgets so elementary for them to look like QtQuickControls. Give a ruler and a pencil to a child and tell him to draw something by only using them; the result would be Breeze.

Previously, KDE devs always made Qt better than what it was by creating more practical Qt objects. For example, KDE3 was far better than Qt3 and the same could be said about KDE4 to some extent. But now, it seems they've started to use an inferior part of Qt. Who knows what will happen if they continue this trend? A file manager in QML?!

**Comment by tsujan** [comment]
FYI:
This was the skeuomorphic Oxygen:

![oxygen](https://user-images.githubusercontent.com/981076/34776946-d3653336-f62d-11e7-9f9f-5eba40166e36.png)

This is the Win95-like Breeze:

![breeze](https://user-images.githubusercontent.com/981076/34776956-e166f7ee-f62d-11e7-8cb4-6871eebfe0d5.png)

What a regression!

**Comment by nowrep** [comment]
Alright, but that's not a topic of this issue.

QtQuickControls1 desktop style sucks, it could be better, but it can be handled quite well in a QStyle. It is now deprecated and QtQuickControls2 no longer use QStyle, so there is really no point discussing this. It will not get better :D

This bug is now being fixed: https://phabricator.kde.org/D9784 https://phabricator.kde.org/D9785

**Comment by tsujan** [comment]
> and QtQuickControls2 no longer use QStyle,

That will be a disaster. It means discrepancy in Qt itself?! We always wanted a unified look for Qt+GTK; now Qt is divided?

**Comment by tsujan** [comment]
Ah... Sometimes I even think about returning to GTK...

**Comment by nowrep** [comment]
QML is not a good fit for desktop interface, you can still use QtWidgets.

**Comment by tsujan** [comment]
> QML is not a good fit for desktop interface, you can still use QtWidgets.

I joked about returning to GTK and I *will* use Qt+C++. The problem is that KDE devs use QML. I even don't use KDE but feel sad seeing its demise -- if any. It was the King of Desktop Environments (KDE).

**Comment by tsujan** [comment]
Off topic or not:

[qqc2-desktop-style](https://github.com/KDE/qqc2-desktop-style) says, "This is a style for QtQuickControls 2 that uses QWidget's QStyle for painting, making possible to achieve a higher degree of consistency between QWidget-based and QML-based apps."

I'm pretty sure that it's Breeze-oriented and so, lame. Apparently, KDE is going in the direction of Gnome: style monopoly.

**Comment by nowrep** [comment]
That is KDE project and not Qt project and it has nothing to do with Breeze. I don't really get what you have against it :D You don't have to use it if you don't like it.

qqc2-desktop-style is a port of desktop style from qqc1 to qqc2, something that Qt decided to not support anymore. So if anything, you should be glad for KDE to pick it up and make qqc2 apps look as consistent with other "toolkits" (qqc1, qtwidgets) as possible. This works with any QStyle, not just Breeze ...

Are you aware that QtWidgets module is considered "Done" by Qt and all focus is shifted to QML? It has nothing to do with KDE...

**Comment by tsujan** [comment]
> I don't really get what you have against it 

Lack of customizability or theme monopoly. Didn't I say it clearly above?

> You don't have to use it if you don't like it.

That's a Gnome attitude.

> Are you aware that QtWidgets module is considered "Done" by Qt and all focus is shifted to QML?

A very unclear statement, especially the word "done".

As this is off topic, let's stop it here!

**Comment by nowrep** [comment]
> As this is off topic, let's stop it here!

Please explain "Lack of customizability or theme monopoly" before. This is just not true, you can use any style you want and this KDE project (qqc2-desktop-style) makes it possible for existing QStyle styles to be used with QtQuickControls2. It's just the complete opposite of what you are saying, sorry.

**Comment by tsujan** [comment]
Quoting myself: "I'm pretty sure that it's Breeze-oriented and so, lame." How am I pretty sure? Based on experience with QStyle and also based on what I know about how some KDE devs misinterpret its parameters.

I don't use what I don't like but I might need to tell my users that I'll support only Qt, not KDE or QML. That won't be easy to understand.

**Comment by ahjolinna** [comment]
okay then....fascinating....I didn't expect this kind of reaction from my bug report...anyway as this is an upstream issue and it seems to have been resolved (or will be), so I will close this bug report as the fix will arrive when ever the next plasma/framework release happens.

I also don't see any point with continuing with this "conversation"
