### ISSUE TITLE
Button highlights are sometimes off-center and generally odd

### ISSUE THREAD

**Issue by dotWAVE** [PapirusDevelopmentTeam/adapta-kde#37]
![screenshot_20180120_134634](https://user-images.githubusercontent.com/2576219/35186924-38966464-fdea-11e7-8603-ef590501a0d0.png)
As seen on top, the oval backdrop is very odd on buttons that are long/include text. The bottom displays an example of a button without text being off-center. (All icon sizes are set to 22x22)

Things are much better in the GTK theme, which displays centered and uses a different shape entirely.
![image](https://user-images.githubusercontent.com/2576219/35186955-b3fb533a-fdea-11e7-8bd6-043795abbe9f.png)

Is it possible within the limits of kvantum themes, to make the KDE style more closely mimic the GTK style? would standardizing on colored underlines be an alternative?

**Comment by varlesh** [comment]
See https://github.com/PapirusDevelopmentTeam/adapta-kde#recommendations:

> For better looking use toolbar icons without text with 22px size 

It's impossible change

**Comment by dotWAVE** [comment]
What about using rectangles instead of ovals?

**Comment by varlesh** [comment]
Rectanle it's not Adapta style... If change oval to rectangle we lose compatibility with GTK Theme. It's will be different!
Without text it's looking not bad (i know, not ideal, but)...
![image](https://user-images.githubusercontent.com/8083855/35187486-e04d44ea-fe3d-11e7-8f89-591fc9bb63b0.png)
Maybe kvantum dev @tsujan can add option for not streched `topright`, `topleft`, `bottomright` & `bottomleft `objects for buttons ... And i'm not shure it's solved problem or not

**Comment by varlesh** [comment]
@tsujsn It's possible streched only `normal`, `normal-top` & `normal-bottom` objects?
Also not strech `topright`, `topleft`, `bottomright` & `bottomleft` objects on horizontaly only?

**Comment by dotWAVE** [comment]
So it is a limitation of kvantum theming. While I would like to be able to have some buttons with icon+text, it looks good enough without. Hopefully some work can be done by @tsujsn in kvantum, or by the KDE team to improve theme support in an official capacity.

Either way, this is still the best KDE theme.

**Comment by varlesh** [comment]
KDE Team not related to Kvantum engine

**Comment by dotWAVE** [comment]
I'm aware. But that is not what I meant.

**Comment by tsujan** [comment]
@varlesh 

(1) In Kvantum, you can't make a button rounded by giving it a rounded interior because, as is mentioned here, a Qt tool button can have text and its text can be beside its icon or under it. Actually, a Qt tool button can have text *without* icon too. Kvantum doesn't support rounded interiors because of this difference between GTK and Qt.

I still have no plan to make an exception for textless buttons because that would make the code too complex, but who knows what might happen later. Until then (which may mean always), if you want your theme to be self-consistent, you'll have to remove those rounded interiors.

(2) In Kvantum, it's possible to have completely rounded corners for buttons or other widgets by using a method called "frame expansion". Please see `Theme-Making.pdf → Maximum Corner Roundness (Frame Expansion)` and also check the themes KvCurves3d and/or KvCurvesLight. When the frame expansion is used, it is for *all* states.

(3) In the GTK Adapta theme, the *title-bar* buttons can have rounded interiors, not the toolbar buttons. Please see the attached screenshot of `gtk3-widget-factory` with Adapta (the same is true for Adapta-Nokto)! Anyhow, Qt and GTK have different concepts of "tool button".

![gtk](https://user-images.githubusercontent.com/981076/35188077-94c61ed2-fe44-11e7-9a3d-3360309f4cc3.png)

**Comment by romanlex** [comment]
Can confirm 
![image](https://user-images.githubusercontent.com/3369304/35977913-57f8d12e-0cf5-11e8-8c3f-8eff42834643.png)

**Comment by varlesh** [comment]
fixed

**Comment by tsujan** [comment]
Confirming that it's OK now. Thanks!
