### ISSUE TITLE
Context Menus doesn't blurring (blur kde effect)

### ISSUE THREAD

**Issue by aislanmaia** [PapirusDevelopmentTeam/adapta-kde#59]
With the KDE 5.13 release, is possible to use a neat blur effect in the windows and context menus. But enabling the blur and translucent related settings in kvantum manager or adapta.kvconfig file, just some windows and blurred. How to get this same effect like the Breeze theme ?

**Comment by varlesh** [comment]
I think kvantum support only transparency without blur... Ask about that on Kvantum developer

**Comment by archqob** [comment]
https://github.com/tsujan/Kvantum/issues/215

**Comment by varlesh** [comment]
@archqob Transparent version not like me, because GTK3-apps not support that on KDE.
Applications looking different :(
If GTK3 engine add support transparency on KDE - i'm add support for Kvantum Themes.
I'm write about this earlier on Arc Themes: https://github.com/PapirusDevelopmentTeam/arc-kde/issues/59
Also Adapta/Materia not used opacity on GTK/Shell Themes - it's not Material style.
But this possible... Need add opacity for menu, tooltip, header and some elements on SVG. Enable opacity in Configigure Active Theme/Compositing on kvantummanager. Set opacity percent.
 It's example with Materia Dark:
![image](https://user-images.githubusercontent.com/8083855/41806755-b502a0ae-76d4-11e8-9036-a154da15d9cb.png)
![image](https://user-images.githubusercontent.com/8083855/41806776-f6e11320-76d4-11e8-99eb-f5cfa5c4770a.png)
Compare GTK3 and Qt5:
![image](https://user-images.githubusercontent.com/8083855/41806790-265d6428-76d5-11e8-95f9-be5f3ba35062.png)
[MateriaDarkTr.tar.gz](https://github.com/PapirusDevelopmentTeam/adapta-kde/files/2129716/MateriaDarkTr.tar.gz)

**Comment by archqob** [comment]
@varlesh yup, you are right about that. thanks for clarification
