### ISSUE TITLE
Icon of redesigned Media Player widget in Plasma 5.13

### ISSUE THREAD

**Issue by pshe94** [PapirusDevelopmentTeam/adapta-kde#62]
In Plasma 5.13 Media Player widget has been redesigned, and now uses different icons in system tray and small sized desktop widget.

This is how the icon in system tray looks like right now with Adapta desktop theme:
![](https://user-images.githubusercontent.com/34661843/41500910-0175027c-719b-11e8-8bce-a654f79cf2b3.png)

**Comment by varlesh** [comment]
this already fixed https://github.com/PapirusDevelopmentTeam/adapta-kde/commit/84c7fd5ce2a28a22d69c75741406a1cdf0781897

**Comment by pshe94** [comment]
But unfortunately, that fix does not work for me. I've replaced original file with the fixed one and icon is still broken. I've already checked the permissions, ownership of the file and checksums. File is identical to the fixed one. Permission and ownership are the same as the rest of files in `icons` folder.

**Comment by varlesh** [comment]
try clear cache and restart plasmashell session:
`rm -rf ~/.cache/plasm* ~/.cache/ico*`

**Comment by now-im** [comment]
@varlesh clearing cache didn't solve my problem.

**Comment by varlesh** [comment]
you update theme from git?

**Comment by varlesh** [comment]
media icons updated! See commits https://github.com/PapirusDevelopmentTeam/adapta-kde/commit/84c7fd5ce2a28a22d69c75741406a1cdf0781897
or open media.svg and check (3 icons for plasma-browser-integration):

- media-playback-playing
- media-playback-paused
- media-playback-stopped

![image](https://user-images.githubusercontent.com/8083855/41512079-471a9932-7294-11e8-8ace-5c557ce49f69.png)

**Comment by flipwise** [comment]
@now-im nothing worked for me either until I realized I had installed Adapta through Get New Stuff before. This old version stuck around and was constantly overriding the package version of Adapta. The solution was to remove Adapta through Get New Stuff and then close system settings and when you start it again the proper Adapta will show up. 

@varlesh maybe it would be a good idea to add an instruction in the script file to delete the Adapta that was installed through Get New Stuff so that it doesn't interfere with the package? I have no clue where these files are stored though.
