### ISSUE TITLE
[Feature request] A script for adjusting the transparency/blur of the panel/widget background

### ISSUE THREAD

**Issue by trmdi** [PapirusDevelopmentTeam/adapta-kde#70]
I think many people like the transparent/blurred background than the solid one (opacity 100%). Something like [BreezeAlpha Black Control](https://github.com/Zren/plasma-applet-alphablackcontrol)

**Comment by varlesh** [comment]
With Blur and opacity already available version Materia Blur:
https://github.com/PapirusDevelopmentTeam/materia-kde
![image](https://user-images.githubusercontent.com/8083855/43629143-7d9a9190-970d-11e8-9865-523732b6fc44.png)

**Comment by trmdi** [comment]
But I prefer Adapta-KDE. Can you point me how to manually change:
- The transparency of the widget background/ notification... ?
- Add the blurred effect (if it's needed to tell Plasma to apply the effect) ?

**Comment by varlesh** [comment]
> The transparency of the widget background/ notification... ?

Adapta very similar with Materia's themes. 
You can compare Materia Blur and Materia Dark kvantum and plasma widgets SVG's for different.
For example, for `tooltip` & `background` widgets on plasma added 10% opacity and etc...
More info here:
https://techbase.kde.org/Development/Tutorials/Plasma5/ThemeDetails

For opacity background on Kvantum theme need added alphachannel  to `base.color` and `alt.base.color` (this worked good with latest kvantum engine)
More info you can find here:
https://github.com/tsujan/Kvantum/blob/master/Kvantum/doc/Theme-Making.pdf
https://github.com/tsujan/Kvantum/blob/master/Kvantum/doc/Theme-Config.pdf

> Add the blurred effect (if it's needed to tell Plasma to apply the effect) ?

Blur effect on KDE enabled on systemsettings.

PS: Materia Blur - it's experimental theme only. I'm not seen reason make Adapta Blur version or added support KDE Color Scheme, because GTK upstream not use opacity or different color schemes. My themes created for more compabillity with GTK.

**Comment by trmdi** [comment]
> My themes created for more compabillity with GTK.

Yes, but afaik Adapta-KDE has become one of the most popular desktop themes for Plasma.
Thank you, I'll look into your guide.
